/**
 * High-Profile Financial Asset Universe
 * Master curated list of high-liquidity financial instruments
 * mapped with exact TradingView-compatible embed symbols and Yahoo Finance tickers.
 */

const ASSET_UNIVERSE = [
  // ==========================================
  // 1. FOREX (28 MAJOR & CROSS PAIRS)
  // ==========================================
  { ticker: 'EURUSD', name: 'Euro / US Dollar', category: 'FOREX', tvSymbol: 'OANDA:EURUSD', yahooTicker: 'EURUSD=X', currency: 'USD' },
  { ticker: 'GBPUSD', name: 'British Pound / US Dollar', category: 'FOREX', tvSymbol: 'OANDA:GBPUSD', yahooTicker: 'GBPUSD=X', currency: 'USD' },
  { ticker: 'USDJPY', name: 'US Dollar / Japanese Yen', category: 'FOREX', tvSymbol: 'OANDA:USDJPY', yahooTicker: 'USDJPY=X', currency: 'JPY' },
  { ticker: 'USDCHF', name: 'US Dollar / Swiss Franc', category: 'FOREX', tvSymbol: 'OANDA:USDCHF', yahooTicker: 'USDCHF=X', currency: 'CHF' },
  { ticker: 'USDCAD', name: 'US Dollar / Canadian Dollar', category: 'FOREX', tvSymbol: 'OANDA:USDCAD', yahooTicker: 'USDCAD=X', currency: 'CAD' },
  { ticker: 'AUDUSD', name: 'Australian Dollar / US Dollar', category: 'FOREX', tvSymbol: 'OANDA:AUDUSD', yahooTicker: 'AUDUSD=X', currency: 'USD' },
  { ticker: 'NZDUSD', name: 'New Zealand Dollar / US Dollar', category: 'FOREX', tvSymbol: 'OANDA:NZDUSD', yahooTicker: 'NZDUSD=X', currency: 'USD' },
  { ticker: 'EURGBP', name: 'Euro / British Pound', category: 'FOREX', tvSymbol: 'OANDA:EURGBP', yahooTicker: 'EURGBP=X', currency: 'GBP' },
  { ticker: 'EURJPY', name: 'Euro / Japanese Yen', category: 'FOREX', tvSymbol: 'OANDA:EURJPY', yahooTicker: 'EURJPY=X', currency: 'JPY' },
  { ticker: 'EURCHF', name: 'Euro / Swiss Franc', category: 'FOREX', tvSymbol: 'OANDA:EURCHF', yahooTicker: 'EURCHF=X', currency: 'CHF' },
  { ticker: 'EURCAD', name: 'Euro / Canadian Dollar', category: 'FOREX', tvSymbol: 'OANDA:EURCAD', yahooTicker: 'EURCAD=X', currency: 'CAD' },
  { ticker: 'EURAUD', name: 'Euro / Australian Dollar', category: 'FOREX', tvSymbol: 'OANDA:EURAUD', yahooTicker: 'EURAUD=X', currency: 'AUD' },
  { ticker: 'EURNZD', name: 'Euro / New Zealand Dollar', category: 'FOREX', tvSymbol: 'OANDA:EURNZD', yahooTicker: 'EURNZD=X', currency: 'NZD' },
  { ticker: 'GBPJPY', name: 'British Pound / Japanese Yen', category: 'FOREX', tvSymbol: 'OANDA:GBPJPY', yahooTicker: 'GBPJPY=X', currency: 'JPY' },
  { ticker: 'GBPCHF', name: 'British Pound / Swiss Franc', category: 'FOREX', tvSymbol: 'OANDA:GBPCHF', yahooTicker: 'GBPCHF=X', currency: 'CHF' },
  { ticker: 'GBPCAD', name: 'British Pound / Canadian Dollar', category: 'FOREX', tvSymbol: 'OANDA:GBPCAD', yahooTicker: 'GBPCAD=X', currency: 'CAD' },
  { ticker: 'GBPAUD', name: 'British Pound / Australian Dollar', category: 'FOREX', tvSymbol: 'OANDA:GBPAUD', yahooTicker: 'GBPAUD=X', currency: 'AUD' },
  { ticker: 'GBPNZD', name: 'British Pound / New Zealand Dollar', category: 'FOREX', tvSymbol: 'OANDA:GBPNZD', yahooTicker: 'GBPNZD=X', currency: 'NZD' },
  { ticker: 'AUDJPY', name: 'Australian Dollar / Japanese Yen', category: 'FOREX', tvSymbol: 'OANDA:AUDJPY', yahooTicker: 'AUDJPY=X', currency: 'JPY' },
  { ticker: 'AUDCAD', name: 'Australian Dollar / Canadian Dollar', category: 'FOREX', tvSymbol: 'OANDA:AUDCAD', yahooTicker: 'AUDCAD=X', currency: 'CAD' },
  { ticker: 'AUDCHF', name: 'Australian Dollar / Swiss Franc', category: 'FOREX', tvSymbol: 'OANDA:AUDCHF', yahooTicker: 'AUDCHF=X', currency: 'CHF' },
  { ticker: 'AUDNZD', name: 'Australian Dollar / New Zealand Dollar', category: 'FOREX', tvSymbol: 'OANDA:AUDNZD', yahooTicker: 'AUDNZD=X', currency: 'NZD' },
  { ticker: 'NZDJPY', name: 'New Zealand Dollar / Japanese Yen', category: 'FOREX', tvSymbol: 'OANDA:NZDJPY', yahooTicker: 'NZDJPY=X', currency: 'JPY' },
  { ticker: 'NZDCAD', name: 'New Zealand Dollar / Canadian Dollar', category: 'FOREX', tvSymbol: 'OANDA:NZDCAD', yahooTicker: 'NZDCAD=X', currency: 'CAD' },
  { ticker: 'NZDCHF', name: 'New Zealand Dollar / Swiss Franc', category: 'FOREX', tvSymbol: 'OANDA:NZDCHF', yahooTicker: 'NZDCHF=X', currency: 'CHF' },
  { ticker: 'CADJPY', name: 'Canadian Dollar / Japanese Yen', category: 'FOREX', tvSymbol: 'OANDA:CADJPY', yahooTicker: 'CADJPY=X', currency: 'JPY' },
  { ticker: 'CADCHF', name: 'Canadian Dollar / Swiss Franc', category: 'FOREX', tvSymbol: 'OANDA:CADCHF', yahooTicker: 'CADCHF=X', currency: 'CHF' },
  { ticker: 'CHFJPY', name: 'Swiss Franc / Japanese Yen', category: 'FOREX', tvSymbol: 'OANDA:CHFJPY', yahooTicker: 'CHFJPY=X', currency: 'JPY' },

  // ==========================================
  // 2. INDICI GLOBALI (GLOBAL INDICES)
  // ==========================================
  { ticker: 'SPX', name: 'S&P 500 Index', category: 'INDICES', tvSymbol: 'FOREXCOM:SPXUSD', yahooTicker: '^GSPC', currency: 'USD' },
  { ticker: 'NDX', name: 'Nasdaq 100 Index', category: 'INDICES', tvSymbol: 'FOREXCOM:NSXUSD', yahooTicker: '^IXIC', currency: 'USD' },
  { ticker: 'DJI', name: 'Dow Jones Industrial Average', category: 'INDICES', tvSymbol: 'FOREXCOM:DJI', yahooTicker: '^DJI', currency: 'USD' },
  { ticker: 'RUT', name: 'Russell 2000 Index', category: 'INDICES', tvSymbol: 'FOREXCOM:RUT', yahooTicker: '^RUT', currency: 'USD' },
  { ticker: 'VIX', name: 'CBOE Volatility Index', category: 'INDICES', tvSymbol: 'TVC:VIX', yahooTicker: '^VIX', currency: 'USD' },
  { ticker: 'DAX', name: 'DAX 40 Index (Germania)', category: 'INDICES', tvSymbol: 'INDEX:DEU40', yahooTicker: '^GDAXI', currency: 'EUR' },
  { ticker: 'CAC', name: 'CAC 40 Index (Francia)', category: 'INDICES', tvSymbol: 'OANDA:FR40EUR', yahooTicker: '^FCHI', currency: 'EUR' },
  { ticker: 'FTSE', name: 'FTSE 100 Index (UK)', category: 'INDICES', tvSymbol: 'OANDA:UK100GBP', yahooTicker: '^FTSE', currency: 'GBP' },
  { ticker: 'FTMIB', name: 'FTSE MIB Index (Italia)', category: 'INDICES', tvSymbol: 'INDEX:FTMIB', yahooTicker: 'FTSEMIB.MI', currency: 'EUR' },
  { ticker: 'IBEX', name: 'IBEX 35 Index (Spagna)', category: 'INDICES', tvSymbol: 'OANDA:ES35EUR', yahooTicker: '^IBEX', currency: 'EUR' },
  { ticker: 'SX5E', name: 'Euro Stoxx 50 Index', category: 'INDICES', tvSymbol: 'OANDA:EU50EUR', yahooTicker: '^STOXX50E', currency: 'EUR' },
  { ticker: 'N225', name: 'Nikkei 225 Index (Giappone)', category: 'INDICES', tvSymbol: 'TVC:NI225', yahooTicker: '^N225', currency: 'JPY' },
  { ticker: 'HSI', name: 'Hang Seng Index (Hong Kong)', category: 'INDICES', tvSymbol: 'OANDA:HK33HKD', yahooTicker: '^HSI', currency: 'HKD' },
  { ticker: 'SHCOMP', name: 'Shanghai Composite (Cina)', category: 'INDICES', tvSymbol: 'SSE:000001', yahooTicker: '000001.SS', currency: 'CNY' },
  { ticker: 'STI', name: 'Straits Times Index (Singapore)', category: 'INDICES', tvSymbol: 'SGX:STI', yahooTicker: '^STI', currency: 'SGD' },
  { ticker: 'SENSEX', name: 'BSE Sensex Index (India)', category: 'INDICES', tvSymbol: 'BSE:SENSEX', yahooTicker: '^BSESN', currency: 'INR' },
  { ticker: 'TSX', name: 'S&P/TSX Composite (Canada)', category: 'INDICES', tvSymbol: 'TSX:OSPTX', yahooTicker: '^GSPTSE', currency: 'CAD' },
  { ticker: 'AS51', name: 'ASX 200 Index (Australia)', category: 'INDICES', tvSymbol: 'OANDA:AU200AUD', yahooTicker: '^AS51', currency: 'AUD' },
  { ticker: 'SSMI', name: 'Swiss Market Index (Svizzera)', category: 'INDICES', tvSymbol: 'SIX:SMI', yahooTicker: '^SSMI', currency: 'CHF' },
  { ticker: 'OMX', name: 'OMX Stockholm 30 (Svezia)', category: 'INDICES', tvSymbol: 'NASDAQ:OMXS30', yahooTicker: '^OMX', currency: 'SEK' },
  { ticker: 'OSLO', name: 'Oslo OBX Index (Norvegia)', category: 'INDICES', tvSymbol: 'OSL:OBX', yahooTicker: '^OSLO', currency: 'NOK' },
  { ticker: 'BVSP', name: 'Bovespa Index (Brasile)', category: 'INDICES', tvSymbol: 'BMFBOVESPA:IBOV', yahooTicker: '^BVSP', currency: 'BRL' },
  { ticker: 'MXX', name: 'IPC Index (Messico)', category: 'INDICES', tvSymbol: 'BMV:ME', yahooTicker: '^MXX', currency: 'MXN' },
  { ticker: 'KOSPI', name: 'KOSPI Index (Corea)', category: 'INDICES', tvSymbol: 'KRX:KOSPI', yahooTicker: '^KS11', currency: 'KRW' },
  { ticker: 'VGK', name: 'Vanguard FTSE Europe ETF', category: 'INDICES', tvSymbol: 'AMEX:VGK', yahooTicker: 'VGK', currency: 'USD' },
  { ticker: 'EWC', name: 'iShares MSCI Canada ETF', category: 'INDICES', tvSymbol: 'AMEX:EWC', yahooTicker: 'EWC', currency: 'USD' },
  { ticker: 'EWA', name: 'iShares MSCI Australia ETF', category: 'INDICES', tvSymbol: 'AMEX:EWA', yahooTicker: 'EWA', currency: 'USD' },
  { ticker: 'MCHI', name: 'iShares MSCI China ETF', category: 'INDICES', tvSymbol: 'NASDAQ:MCHI', yahooTicker: 'MCHI', currency: 'USD' },
  { ticker: 'EEM', name: 'iShares MSCI Emerging Markets ETF', category: 'INDICES', tvSymbol: 'AMEX:EEM', yahooTicker: 'EEM', currency: 'USD' },

  // ==========================================
  // 3. COMMODITIES (STRICTLY ISOLATED)
  // ==========================================
  { ticker: 'XAUUSD', name: 'Oro Spot (Gold)', category: 'COMMODITIES', tvSymbol: 'OANDA:XAUUSD', yahooTicker: 'GC=F', currency: 'USD' },
  { ticker: 'XAGUSD', name: 'Argento Spot (Silver)', category: 'COMMODITIES', tvSymbol: 'OANDA:XAGUSD', yahooTicker: 'SI=F', currency: 'USD' },
  { ticker: 'WTI', name: 'Petrolio WTI (Crude Oil)', category: 'COMMODITIES', tvSymbol: 'TVC:USOIL', yahooTicker: 'CL=F', currency: 'USD' },
  { ticker: 'BRENT', name: 'Petrolio Brent (Brent Crude)', category: 'COMMODITIES', tvSymbol: 'TVC:UKOIL', yahooTicker: 'BZ=F', currency: 'USD' },
  { ticker: 'NATGAS', name: 'Gas Naturale (Natural Gas)', category: 'COMMODITIES', tvSymbol: 'TVC:NATGAS', yahooTicker: 'NG=F', currency: 'USD' },
  { ticker: 'COPPER', name: 'Rame High Grade (Copper)', category: 'COMMODITIES', tvSymbol: 'TVC:COPPER', yahooTicker: 'HG=F', currency: 'USD' },
  { ticker: 'PLATINUM', name: 'Platino Spot (Platinum)', category: 'COMMODITIES', tvSymbol: 'TVC:PLATINUM', yahooTicker: 'PL=F', currency: 'USD' },
  { ticker: 'PALLADIUM', name: 'Palladio Spot (Palladium)', category: 'COMMODITIES', tvSymbol: 'TVC:PALLADIUM', yahooTicker: 'PA=F', currency: 'USD' },
  { ticker: 'ALUMINUM', name: 'Alluminio Primario', category: 'COMMODITIES', tvSymbol: 'TVC:ALUMINUM', yahooTicker: 'ALI=F', currency: 'USD' },
  { ticker: 'GLD', name: 'SPDR Gold Shares ETF', category: 'COMMODITIES', tvSymbol: 'AMEX:GLD', yahooTicker: 'GLD', currency: 'USD' },
  { ticker: 'SLV', name: 'iShares Silver Trust ETF', category: 'COMMODITIES', tvSymbol: 'AMEX:SLV', yahooTicker: 'SLV', currency: 'USD' },
  { ticker: 'USO', name: 'United States Oil Fund LP', category: 'COMMODITIES', tvSymbol: 'AMEX:USO', yahooTicker: 'USO', currency: 'USD' },
  { ticker: 'URA', name: 'Global X Uranium ETF', category: 'COMMODITIES', tvSymbol: 'AMEX:URA', yahooTicker: 'URA', currency: 'USD' },
  { ticker: 'DBA', name: 'Invesco DB Agriculture Fund', category: 'COMMODITIES', tvSymbol: 'AMEX:DBA', yahooTicker: 'DBA', currency: 'USD' },
  { ticker: 'DBC', name: 'Invesco DB Commodity Index', category: 'COMMODITIES', tvSymbol: 'AMEX:DBC', yahooTicker: 'DBC', currency: 'USD' },

  // ==========================================
  // 4. CRIPTOVALUTE (CRYPTO)
  // ==========================================
  { ticker: 'BTC', name: 'Bitcoin', category: 'CRYPTO', tvSymbol: 'BINANCE:BTCUSDT', yahooTicker: 'BTC-USD', currency: 'USD' },
  { ticker: 'ETH', name: 'Ethereum', category: 'CRYPTO', tvSymbol: 'BINANCE:ETHUSDT', yahooTicker: 'ETH-USD', currency: 'USD' },
  { ticker: 'SOL', name: 'Solana', category: 'CRYPTO', tvSymbol: 'BINANCE:SOLUSDT', yahooTicker: 'SOL-USD', currency: 'USD' },
  { ticker: 'BNB', name: 'Binance Coin', category: 'CRYPTO', tvSymbol: 'BINANCE:BNBUSDT', yahooTicker: 'BNB-USD', currency: 'USD' },
  { ticker: 'XRP', name: 'Ripple XRP', category: 'CRYPTO', tvSymbol: 'BINANCE:XRPUSDT', yahooTicker: 'XRP-USD', currency: 'USD' },
  { ticker: 'ADA', name: 'Cardano', category: 'CRYPTO', tvSymbol: 'BINANCE:ADAUSDT', yahooTicker: 'ADA-USD', currency: 'USD' },
  { ticker: 'LINK', name: 'Chainlink', category: 'CRYPTO', tvSymbol: 'BINANCE:LINKUSDT', yahooTicker: 'LINK-USD', currency: 'USD' },
  { ticker: 'AVAX', name: 'Avalanche', category: 'CRYPTO', tvSymbol: 'BINANCE:AVAXUSDT', yahooTicker: 'AVAX-USD', currency: 'USD' },
  { ticker: 'DOGE', name: 'Dogecoin', category: 'CRYPTO', tvSymbol: 'BINANCE:DOGEUSDT', yahooTicker: 'DOGE-USD', currency: 'USD' },
  { ticker: 'DOT', name: 'Polkadot', category: 'CRYPTO', tvSymbol: 'BINANCE:DOTUSDT', yahooTicker: 'DOT-USD', currency: 'USD' },
  { ticker: 'NEAR', name: 'NEAR Protocol', category: 'CRYPTO', tvSymbol: 'BINANCE:NEARUSDT', yahooTicker: 'NEAR-USD', currency: 'USD' },
  { ticker: 'UNI', name: 'Uniswap', category: 'CRYPTO', tvSymbol: 'BINANCE:UNIUSDT', yahooTicker: 'UNI-USD', currency: 'USD' },
  { ticker: 'LTC', name: 'Litecoin', category: 'CRYPTO', tvSymbol: 'BINANCE:LTCUSDT', yahooTicker: 'LTC-USD', currency: 'USD' },
  { ticker: 'POL', name: 'Polygon', category: 'CRYPTO', tvSymbol: 'BINANCE:POLUSDT', yahooTicker: 'POL-USD', currency: 'USD' },
  { ticker: 'TON', name: 'Toncoin', category: 'CRYPTO', tvSymbol: 'OKX:TONUSDT', yahooTicker: 'TON-USD', currency: 'USD' },

  // ==========================================
  // 5. AZIONI (TOP 50 MEGA-CAP GLOBALI & EQUITY SECTOR ETFS)
  // ==========================================
  { ticker: 'NVDA', name: 'NVIDIA Corporation', category: 'EQUITY', tvSymbol: 'NASDAQ:NVDA', yahooTicker: 'NVDA', currency: 'USD' },
  { ticker: 'AAPL', name: 'Apple Inc.', category: 'EQUITY', tvSymbol: 'NASDAQ:AAPL', yahooTicker: 'AAPL', currency: 'USD' },
  { ticker: 'MSFT', name: 'Microsoft Corporation', category: 'EQUITY', tvSymbol: 'NASDAQ:MSFT', yahooTicker: 'MSFT', currency: 'USD' },
  { ticker: 'AMZN', name: 'Amazon.com Inc.', category: 'EQUITY', tvSymbol: 'NASDAQ:AMZN', yahooTicker: 'AMZN', currency: 'USD' },
  { ticker: 'GOOGL', name: 'Alphabet Inc. (Google)', category: 'EQUITY', tvSymbol: 'NASDAQ:GOOGL', yahooTicker: 'GOOGL', currency: 'USD' },
  { ticker: 'META', name: 'Meta Platforms Inc.', category: 'EQUITY', tvSymbol: 'NASDAQ:META', yahooTicker: 'META', currency: 'USD' },
  { ticker: 'TSLA', name: 'Tesla Inc.', category: 'EQUITY', tvSymbol: 'NASDAQ:TSLA', yahooTicker: 'TSLA', currency: 'USD' },
  { ticker: 'AVGO', name: 'Broadcom Inc.', category: 'EQUITY', tvSymbol: 'NASDAQ:AVGO', yahooTicker: 'AVGO', currency: 'USD' },
  { ticker: 'ORCL', name: 'Oracle Corporation', category: 'EQUITY', tvSymbol: 'NYSE:ORCL', yahooTicker: 'ORCL', currency: 'USD' },
  { ticker: 'PLTR', name: 'Palantir Technologies Inc.', category: 'EQUITY', tvSymbol: 'NASDAQ:PLTR', yahooTicker: 'PLTR', currency: 'USD' },
  { ticker: 'AMD', name: 'Advanced Micro Devices', category: 'EQUITY', tvSymbol: 'NASDAQ:AMD', yahooTicker: 'AMD', currency: 'USD' },
  { ticker: 'INTC', name: 'Intel Corporation', category: 'EQUITY', tvSymbol: 'NASDAQ:INTC', yahooTicker: 'INTC', currency: 'USD' },
  { ticker: 'QCOM', name: 'QUALCOMM Incorporated', category: 'EQUITY', tvSymbol: 'NASDAQ:QCOM', yahooTicker: 'QCOM', currency: 'USD' },
  { ticker: 'CRM', name: 'Salesforce Inc.', category: 'EQUITY', tvSymbol: 'NYSE:CRM', yahooTicker: 'CRM', currency: 'USD' },
  { ticker: 'ADBE', name: 'Adobe Inc.', category: 'EQUITY', tvSymbol: 'NASDAQ:ADBE', yahooTicker: 'ADBE', currency: 'USD' },
  { ticker: 'NFLX', name: 'Netflix Inc.', category: 'EQUITY', tvSymbol: 'NASDAQ:NFLX', yahooTicker: 'NFLX', currency: 'USD' },
  { ticker: 'UBER', name: 'Uber Technologies Inc.', category: 'EQUITY', tvSymbol: 'NYSE:UBER', yahooTicker: 'UBER', currency: 'USD' },
  { ticker: 'NOW', name: 'ServiceNow Inc.', category: 'EQUITY', tvSymbol: 'NYSE:NOW', yahooTicker: 'NOW', currency: 'USD' },
  { ticker: 'IBM', name: 'International Business Machines', category: 'EQUITY', tvSymbol: 'NYSE:IBM', yahooTicker: 'IBM', currency: 'USD' },
  { ticker: 'BRK-B', name: 'Berkshire Hathaway', category: 'EQUITY', tvSymbol: 'NYSE:BRK.B', yahooTicker: 'BRK-B', currency: 'USD' },
  { ticker: 'JPM', name: 'JPMorgan Chase & Co.', category: 'EQUITY', tvSymbol: 'NYSE:JPM', yahooTicker: 'JPM', currency: 'USD' },
  { ticker: 'V', name: 'Visa Inc.', category: 'EQUITY', tvSymbol: 'NYSE:V', yahooTicker: 'V', currency: 'USD' },
  { ticker: 'MA', name: 'Mastercard Incorporated', category: 'EQUITY', tvSymbol: 'NYSE:MA', yahooTicker: 'MA', currency: 'USD' },
  { ticker: 'BAC', name: 'Bank of America Corp.', category: 'EQUITY', tvSymbol: 'NYSE:BAC', yahooTicker: 'BAC', currency: 'USD' },
  { ticker: 'GS', name: 'The Goldman Sachs Group', category: 'EQUITY', tvSymbol: 'NYSE:GS', yahooTicker: 'GS', currency: 'USD' },
  { ticker: 'MS', name: 'Morgan Stanley', category: 'EQUITY', tvSymbol: 'NYSE:MS', yahooTicker: 'MS', currency: 'USD' },
  { ticker: 'WMT', name: 'Walmart Inc.', category: 'EQUITY', tvSymbol: 'NYSE:WMT', yahooTicker: 'WMT', currency: 'USD' },
  { ticker: 'COST', name: 'Costco Wholesale Corp.', category: 'EQUITY', tvSymbol: 'NASDAQ:COST', yahooTicker: 'COST', currency: 'USD' },
  { ticker: 'HD', name: 'The Home Depot Inc.', category: 'EQUITY', tvSymbol: 'NYSE:HD', yahooTicker: 'HD', currency: 'USD' },
  { ticker: 'MCD', name: "McDonald's Corporation", category: 'EQUITY', tvSymbol: 'NYSE:MCD', yahooTicker: 'MCD', currency: 'USD' },
  { ticker: 'NKE', name: 'NIKE Inc.', category: 'EQUITY', tvSymbol: 'NYSE:NKE', yahooTicker: 'NKE', currency: 'USD' },
  { ticker: 'PG', name: 'The Procter & Gamble Company', category: 'EQUITY', tvSymbol: 'NYSE:PG', yahooTicker: 'PG', currency: 'USD' },
  { ticker: 'KO', name: 'The Coca-Cola Company', category: 'EQUITY', tvSymbol: 'NYSE:KO', yahooTicker: 'KO', currency: 'USD' },
  { ticker: 'PEP', name: 'PepsiCo Inc.', category: 'EQUITY', tvSymbol: 'NASDAQ:PEP', yahooTicker: 'PEP', currency: 'USD' },
  { ticker: 'DIS', name: 'The Walt Disney Company', category: 'EQUITY', tvSymbol: 'NYSE:DIS', yahooTicker: 'DIS', currency: 'USD' },
  { ticker: 'LLY', name: 'Eli Lilly and Company', category: 'EQUITY', tvSymbol: 'NYSE:LLY', yahooTicker: 'LLY', currency: 'USD' },
  { ticker: 'NVO', name: 'Novo Nordisk A/S', category: 'EQUITY', tvSymbol: 'NYSE:NVO', yahooTicker: 'NVO', currency: 'USD' },
  { ticker: 'UNH', name: 'UnitedHealth Group Incorporated', category: 'EQUITY', tvSymbol: 'NYSE:UNH', yahooTicker: 'UNH', currency: 'USD' },
  { ticker: 'JNJ', name: 'Johnson & Johnson', category: 'EQUITY', tvSymbol: 'NYSE:JNJ', yahooTicker: 'JNJ', currency: 'USD' },
  { ticker: 'ABBV', name: 'AbbVie Inc.', category: 'EQUITY', tvSymbol: 'NYSE:ABBV', yahooTicker: 'ABBV', currency: 'USD' },
  { ticker: 'MRK', name: 'Merck & Co. Inc.', category: 'EQUITY', tvSymbol: 'NYSE:MRK', yahooTicker: 'MRK', currency: 'USD' },
  { ticker: 'CVX', name: 'Chevron Corporation', category: 'EQUITY', tvSymbol: 'NYSE:CVX', yahooTicker: 'CVX', currency: 'USD' },
  { ticker: 'CAT', name: 'Caterpillar Inc.', category: 'EQUITY', tvSymbol: 'NYSE:CAT', yahooTicker: 'CAT', currency: 'USD' },
  { ticker: 'GE', name: 'GE Aerospace', category: 'EQUITY', tvSymbol: 'NYSE:GE', yahooTicker: 'GE', currency: 'USD' },
  { ticker: 'BA', name: 'The Boeing Company', category: 'EQUITY', tvSymbol: 'NYSE:BA', yahooTicker: 'BA', currency: 'USD' },
  { ticker: 'TSM', name: 'Taiwan Semiconductor (TSMC)', category: 'EQUITY', tvSymbol: 'NYSE:TSM', yahooTicker: 'TSM', currency: 'USD' },
  { ticker: 'ASML', name: 'ASML Holding N.V.', category: 'EQUITY', tvSymbol: 'NASDAQ:ASML', yahooTicker: 'ASML', currency: 'EUR' },
  { ticker: 'BABA', name: 'Alibaba Group Holding', category: 'EQUITY', tvSymbol: 'NYSE:BABA', yahooTicker: 'BABA', currency: 'USD' },
  { ticker: 'RACE', name: 'Ferrari N.V.', category: 'EQUITY', tvSymbol: 'NYSE:RACE', yahooTicker: 'RACE', currency: 'EUR' },
  { ticker: 'SPY', name: 'SPDR S&P 500 ETF Trust', category: 'EQUITY', tvSymbol: 'AMEX:SPY', yahooTicker: 'SPY', currency: 'USD' },
  { ticker: 'QQQ', name: 'Invesco QQQ Trust', category: 'EQUITY', tvSymbol: 'NASDAQ:QQQ', yahooTicker: 'QQQ', currency: 'USD' },
  { ticker: 'IWM', name: 'iShares Russell 2000 ETF', category: 'EQUITY', tvSymbol: 'AMEX:IWM', yahooTicker: 'IWM', currency: 'USD' },
  { ticker: 'DIA', name: 'SPDR Dow Jones Industrial ETF', category: 'EQUITY', tvSymbol: 'AMEX:DIA', yahooTicker: 'DIA', currency: 'USD' },
  { ticker: 'VOO', name: 'Vanguard S&P 500 ETF', category: 'EQUITY', tvSymbol: 'AMEX:VOO', yahooTicker: 'VOO', currency: 'USD' },
  { ticker: 'VUG', name: 'Vanguard Growth ETF', category: 'EQUITY', tvSymbol: 'AMEX:VUG', yahooTicker: 'VUG', currency: 'USD' },
  { ticker: 'SMH', name: 'VanEck Semiconductor ETF', category: 'EQUITY', tvSymbol: 'NASDAQ:SMH', yahooTicker: 'SMH', currency: 'USD' },
  { ticker: 'XLK', name: 'Technology Select SPDR Fund', category: 'EQUITY', tvSymbol: 'AMEX:XLK', yahooTicker: 'XLK', currency: 'USD' },
  { ticker: 'XLF', name: 'Financial Select SPDR Fund', category: 'EQUITY', tvSymbol: 'AMEX:XLF', yahooTicker: 'XLF', currency: 'USD' },
  { ticker: 'XLV', name: 'Health Care Select SPDR Fund', category: 'EQUITY', tvSymbol: 'AMEX:XLV', yahooTicker: 'XLV', currency: 'USD' }
];

module.exports = ASSET_UNIVERSE;
